name: dl-py3.9
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - ld_impl_linux-64=2.43=h1423503_5
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgomp=15.1.0=h767d61c_3
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.1=h6cd9bfd_7
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_1
  - pip=25.1.1=pyh8b19718_0
  - python=3.9.23=hc30ae73_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - eval-type-backport==0.2.2
      - filelock==3.18.0
      - fsspec==2025.5.1
      - grpcio==1.73.1
      - hf-xet==1.1.5
      - huggingface-hub==0.33.1
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - lazy-loader==0.4
      - markdown==3.8.2
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.3.0
      - pillow==11.2.1
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - segmentation-models-pytorch==0.5.0
      - simsimd==6.5.0
      - six==1.17.0
      - stringzilla==3.12.5
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==1.0.16
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - triton==3.3.1
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - zipp==3.23.0
prefix: /users/angaran2/anaconda3/envs/dl-py3.9
